version: "3.8"

services:
  traefik:
    container_name: traefik
    image: traefik:v2.10.1
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.django_wagtail.address=:80"
    labels:
      - "traefik.http.routers.api.rule=Host(`localhost`)"
      - "traefik.http.routers.api.service=api@internal"
    networks:
      - webgateway
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/var/docker/traefik.yml:/traefik.yml"
    restart: "unless-stopped"

networks:
  webgateway:
    driver: "bridge"
