log:
  level: INFO

accessLog: {}

api:
  dashboard: true
  insecure: true

entryPoints:
  django-wagtail:
    address: ":80"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true
    network: "dw_web"
