---
name: Web Reverse Proxy NginX AMI
run-name: Web Reverse Proxy NginX AMI rp-nginx-primer-(date-time) in ${{ inputs.account }} by @${{ github.actor }}

permissions:
  id-token: write
  contents: write

on:
  workflow_dispatch:
    inputs:
      account:
        type: choice
        description: AWS account
        required: true
        options:
        - dev
        - staging
        - live

jobs:
# ------------------------------------------------------------------------------
# dev deployment
# ------------------------------------------------------------------------------
  rp-ami-dev:
    if: github.event.inputs.account == 'dev'
    uses: nationalarchives/ds-github-actions/.github/workflows/web-rp-nginx-ami-build.yml@main
    with:
      base_role: "arn:aws:iam::846769538626:role/GithubOIDCProviderIAMRolePermissions-Role-I80RXHT6O1PL"
      playbook_role: "arn:aws:iam::846769538626:role/s-devops-ansible-amis"
      region: "eu-west-2"
      branch: "${{ github.event.inputs.branch }}"
      account: "${{ github.event.inputs.account }}"
      key_name: "web-rp-${{ github.event.inputs.account }}-eu-west-2"
      instance_type: 't3a.small'
      swapfile_size: 6291456
      volume_size: 40
      s3_deployment_bucket: "ds-${{ github.event.inputs.account }}-deployment-source"
      s3_deployment_root: "website/web-rp-nginx"
      s3_logfile_bucket: "ds-${{ github.event.inputs.account }}-logfiles"
      s3_logfile_root: "website/web-rp-nginx"

...
